### PR TITLE
feature: add displays subpackage

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds a new subpackage named `displays` intended to make it easier to use one of the supported display devices.

It also adds a `terminal.Display()` method that is just a wrapper for calling the display's method of the same name. This is required for displays such as e-ink or slow OLED screens.

Even though `display.Display()` is a no-op on many displays, this will ensure compatibility with these slower displays.

This PR requires #12 be merged first and then this one rebased.

### CODE REVIEW

**Comment by deadprogram** [comment]
Rebased against `dev`

**Comment by deadprogram** [comment]
I will also update go mod... stand by.

**Comment by conejoninja** [comment]
Requirements have been met, so now merging. Thanks 👍

**Comment by deadprogram** [comment]
Thanks @conejoninja

**Pull request merged**
